from llm.base import LLMEvaluator
from llm.schemas import CriterionEvaluation, LLMEvaluation


class MockLLMEvaluator(LLMEvaluator):
    """
    Deterministic mock evaluator for development and testing.

    This does not use an external API.
    """

    def evaluate(self, evidence_package: dict) -> LLMEvaluation:
        results = []

        for criterion in evidence_package.get("rubric", []):
            max_score = float(criterion.get("max_score", 0))

            results.append(
                CriterionEvaluation(
                    criterion_id=criterion.get("id", ""),
                    criterion_name=criterion.get("name", ""),
                    score=max_score,
                    max_score=max_score,
                    evidence=[
                        "Mock evaluator response."
                    ],
                    missing_requirements=[],
                    reasoning=(
                        "This result was generated by the development "
                        "mock evaluator and is not a real AI evaluation."
                    ),
                    confidence=0.0,
                )
            )

        return LLMEvaluation(
            criterion_results=results,
            model="mock",
            overall_notes=[
                "Mock evaluation only. No external LLM was called."
            ],
        )